name: Check

on: workflow

jobs:
  deploy:

    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      with:
        node-version: '18.16.0'
      - name: Install npm dependencies
        run: npm ci

      - name: Lint check
        run: npm run lint

      - name: Generate image version
        run: echo "::set-output name=docker-image-version::$(date +%s)"
        id: version
        
      - name: Build the Docker image
        run: docker build . -t volodymyr999/dockerlabv1:${{ steps.version.outputs.docker-image-version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish the image to Docker Hub
        run: docker push volodymyr999/dockerlabv1:${{ steps.version.outputs.docker-image-version }}